### ISSUE TITLE
您好 請問我可以用微信請教您問題嗎

### ISSUE THREAD

**Issue by fatalfeel** [dev-bz/ppo#2]
id: hunhunnetshop
或請您留 下email 連絡 感謝
my email: fatalfeel@hotmail.com

**Comment by fatalfeel** [comment]
https://github.com/Mikoto10032/DeepLearning/blob/master/books/%5B%E6%B7%B1%E5%BA%A6%E5%BC%BA%E5%8C%96%E5%AD%A6%E4%B9%A0%5D%5BHung-yi%20Lee%5D/PPO%20(v3).pdf

in this pdf page 9. formula as this 
𝑝𝜃 𝜏 = 𝑝 𝑠1 𝑝𝜃 𝑎1|𝑠1 𝑝 𝑠2|𝑠1, 𝑎1 𝑝𝜃 𝑎2|𝑠2 𝑝 𝑠3|𝑠2, 𝑎2 ⋯

where is the formula in c++ file? which function implement it? or where define it?
help me find out

**Comment by dev-bz** [comment]
wx：cide-maker
加时注明来自GitHub

**Comment by dev-bz** [comment]
优势估计在c++代码中有(Trainer::postUpdate)，而actor的网络结构在ppo.txt(caffe 格式)中，使用的clip版PPO。
